"""Live UI <-> backend round-trip in OPENCODE mode.

Starts the FastAPI backend with HELPER_DASHBOARD_OPENCODE=opencode
and a realistic stub `opencode` binary on disk (the real CLI isn't
installed in this sandbox). Demonstrates:

  1. Successful subprocess round-trip — responses carry
     runtime_used="opencode".
  2. Strict failure — when the binary is missing or returns invalid
     output, opencode mode refuses to silently fall back; the user
     gets a safe error reply and a DeveloperTicket is filed.
"""

from __future__ import annotations

import json
import os
import shutil
import signal
import stat
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = ROOT / "backend"


STUB_BODY = r"""#!/usr/bin/env python3
import json, sys, uuid

payload = json.loads(sys.stdin.read())
op = payload["operation"]
args = payload.get("args") or {}

def user_message():
    msg = (args.get("message") or "").lower()
    current = args.get("current_dashboard_id")
    patch_triggers = ("add", "remove", "delete", "change", "update",
                      "set", "rename", "move", "resize")
    if current and any(t in msg for t in patch_triggers):
        return {
            "type": "PatchIntent",
            "target_dashboard_id": current,
            "requested_changes": [args.get("message", "")],
            "message_to_user": "Patching via real OpenCode.",
        }
    if any(t in msg for t in ("dashboard", "chart", "show me", "monitor")):
        return {
            "type": "DashboardIntent",
            "summary": "via real OpenCode",
            "requirements": {
                "title": "Real OpenCode Demo",
                "goal": args.get("message", ""),
                "metrics_hints": ["up", "http_requests_total"],
                "widget_hints": ["line_chart", "stat_card"],
                "refresh_interval_hint": "30s",
            },
            "clarification_needed": False,
            "message_to_user": "On it - using real OpenCode.",
        }
    return {"type": "UserResponse",
            "message": "Real OpenCode says: what dashboard do you want?"}

def generate_dashboard():
    return {
        "type": "DashboardSpec",
        "spec": {
            "dashboard_id": "opencode-demo",
            "title": "OpenCode Runtime Demo",
            "description": "Generated by the real OpenCode stub.",
            "layout": {"columns": 12, "row_height": 40},
            "variables": [],
            "widgets": [
                {"id": "w-up",
                 "type": "stat_card",
                 "title": "Targets up",
                 "description": "",
                 "query": {"source": "prometheus",
                           "promql": "sum(up)",
                           "query_type": "instant"},
                 "position": {"x": 0, "y": 0, "w": 3, "h": 4},
                 "encoding": {"unit": ""},
                 "thresholds": [], "options": {}},
                {"id": "w-req",
                 "type": "line_chart",
                 "title": "HTTP req/s",
                 "description": "",
                 "query": {"source": "prometheus",
                           "promql": "rate(http_requests_total[5m])",
                           "query_type": "range",
                           "range": "1h",
                           "step": "30s"},
                 "position": {"x": 3, "y": 0, "w": 9, "h": 6},
                 "encoding": {"unit": "req/s"},
                 "thresholds": [], "options": {}},
            ],
            "refresh_interval": "30s",
        },
    }

def patch_dashboard():
    dashboard = args.get("dashboard") or {}
    return {
        "type": "PatchSpec",
        "spec": {
            "patch_id": "p-" + uuid.uuid4().hex[:8],
            "reason": "add a gauge for memory",
            "target_dashboard_id": dashboard.get("dashboard_id"),
            "created_by": "patch-agent",
            "operations": [{
                "op": "add_widget",
                "widget": {
                    "id": "w-mem",
                    "type": "gauge",
                    "title": "Memory available",
                    "description": "",
                    "query": {"source": "prometheus",
                              "promql": "avg(node_memory_MemAvailable_bytes)",
                              "query_type": "instant"},
                    "position": {"x": 0, "y": 6, "w": 3, "h": 4},
                    "encoding": {"unit": "bytes"},
                    "thresholds": [],
                    "options": {"min": 0, "max": 100},
                },
            }],
        },
    }

handlers = {
    "user_message": user_message,
    "generate_dashboard": generate_dashboard,
    "patch_dashboard": patch_dashboard,
}
if op in handlers:
    print(json.dumps(handlers[op]()))
else:
    print(json.dumps({"type": "UserResponse", "message": "noop"}))
"""


def post(url, body, timeout=8):
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(),
        headers={"content-type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, json.loads(r.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


def get(url, timeout=5):
    with urllib.request.urlopen(url, timeout=timeout) as r:
        return r.status, r.read()


def wait_healthy(tries=30):
    for _ in range(tries):
        try:
            s, _ = get("http://127.0.0.1:8000/api/health", timeout=1)
            if s == 200:
                return True
        except Exception:
            pass
        time.sleep(0.5)
    return False


def start_backend(env_extra):
    env = {**os.environ, "PYTHONPATH": str(BACKEND_DIR), **env_extra}
    return subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "app.main:app",
         "--host", "127.0.0.1", "--port", "8000", "--log-level", "warning"],
        env=env, cwd=str(BACKEND_DIR),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


def stop(proc):
    try:
        os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
        proc.wait(timeout=5)
    except Exception:
        try: proc.kill()
        except Exception: pass


def hr(c="="): print(c * 72)
def banner(t): hr(); print("  " + t); hr()
def sub(t): print(f"\n--- {t} ---")


def main():
    tmpdir = Path(tempfile.mkdtemp(prefix="opencode-stub-"))
    stub = tmpdir / "opencode"
    stub.write_text(STUB_BODY)
    stub.chmod(stub.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"stub binary: {stub}")

    # -------------------------------------------------------------------
    banner("PART A — opencode mode SUCCESS (stub plays the real CLI)")
    backend = start_backend({
        "HELPER_DASHBOARD_OPENCODE": "opencode",
        "HELPER_DASHBOARD_OPENCODE_BIN": str(stub),
        "HELPER_DASHBOARD_OPENCODE_CMD": json.dumps(["{bin}"]),
    })
    try:
        assert wait_healthy(), "backend never came up"

        sub("POST /api/chat/message — create")
        s, body = post(
            "http://127.0.0.1:8000/api/chat/message",
            {"session_id": "oc-1",
             "message": "Show me a dashboard from real OpenCode"},
        )
        print(f"  HTTP {s}")
        print(f"  intent_type:   {body['intent_type']}")
        print(f"  runtime_used:  {body['runtime_used']}   <-- real subprocess!")
        print(f"  fallback:      {body['fallback_reason']}")
        print(f"  user_reply:    {body['user_reply']}")
        d = body["dashboard"]
        did = d["dashboard_id"]
        print(f"  dashboard_id:  {did}")
        print(f"  widgets:")
        for w in d["widgets"]:
            print(f"    - {w['id']:10s} type={w['type']:10s} "
                  f"promql={w['query']['promql']}")

        sub("POST /api/chat/message — patch")
        s, body = post(
            "http://127.0.0.1:8000/api/chat/message",
            {"session_id": "oc-1",
             "message": "add a memory gauge",
             "current_dashboard_id": did},
        )
        print(f"  HTTP {s}")
        print(f"  intent_type:   {body['intent_type']}")
        print(f"  runtime_used:  {body['runtime_used']}")
        ops = body["patch"]["operations"]
        print(f"  operations:    {[op['op'] for op in ops]}")
        new_w = ops[0]["widget"]
        print(f"  added widget:  id={new_w['id']} type={new_w['type']} "
              f"promql={new_w['query']['promql']}")
        print(f"  widgets now:   "
              f"{[w['type'] for w in body['dashboard']['widgets']]}")
    finally:
        stop(backend)

    # -------------------------------------------------------------------
    banner("PART B — opencode mode FAILURE (binary missing). NO FALLBACK.")
    backend = start_backend({
        "HELPER_DASHBOARD_OPENCODE": "opencode",
        "HELPER_DASHBOARD_OPENCODE_BIN": "/nonexistent/opencode-xyz",
        "HELPER_DASHBOARD_OPENCODE_CMD": json.dumps(["{bin}"]),
    })
    try:
        assert wait_healthy(), "backend never came up"

        sub("POST /api/chat/message — real binary missing")
        s, body = post(
            "http://127.0.0.1:8000/api/chat/message",
            {"session_id": "oc-fail",
             "message": "Show me a dashboard"},
        )
        print(f"  HTTP {s}")
        print(f"  intent_type:   {body['intent_type']}   <-- NOT DashboardSpec")
        print(f"  runtime_used:  {body['runtime_used']}   <-- None (failed pre-mock)")
        print(f"  user_reply:    {body['user_reply']}")
        print(f"  warnings:      {body['warnings']}")
        print(f"  dashboard:     {body['dashboard']}")
        tickets = sorted(
            (BACKEND_DIR / "app" / "storage" / "tickets").glob("*.json"))
        print(f"  tickets on disk: {[p.name for p in tickets]}")
        if tickets:
            content = json.loads(tickets[-1].read_text())
            print(f"    latest summary: {content['summary']}")
    finally:
        stop(backend)

    # -------------------------------------------------------------------
    banner("PART C — auto mode FAILURE → fallback with explicit marker")
    backend = start_backend({
        "HELPER_DASHBOARD_OPENCODE": "auto",
        "HELPER_DASHBOARD_OPENCODE_BIN": "/nonexistent/opencode-xyz",
        "HELPER_DASHBOARD_OPENCODE_CMD": json.dumps(["{bin}"]),
    })
    try:
        assert wait_healthy(), "backend never came up"
        sub("POST /api/chat/message — auto falls back")
        s, body = post(
            "http://127.0.0.1:8000/api/chat/message",
            {"session_id": "auto-1",
             "message": "Show me a dashboard"},
        )
        print(f"  HTTP {s}")
        print(f"  intent_type:     {body['intent_type']}")
        print(f"  runtime_used:    {body['runtime_used']}   <-- explicit marker")
        print(f"  fallback_reason: {body['fallback_reason']}")
        print(f"  widgets:         "
              f"{[w['type'] for w in body['dashboard']['widgets']]}")
    finally:
        stop(backend)
        shutil.rmtree(tmpdir, ignore_errors=True)

    banner("DONE")


if __name__ == "__main__":
    main()
