apiVersion: 1

datasources:
  # Prometheus 數據源配置
  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      manageAlerts: true
      alertmanagerUid: ""
      httpMethod: POST
      exemplarTraceIdDestinations: []
    secureJsonFields: {}
    version: 1