storage:
  dbPath: mongodb_data/db
  journal:
    enabled: true

systemLog:
  destination: file
  path: mongodb_data/logs/mongod.log
  logAppend: true

net:
  port: 27017
  bindIp: 127.0.0.1

processManagement:
  fork: false

security:
  authorization: disabled
